"""add topic field to Post model

Revision ID: 842b7d247043
Revises: f900173fcc2e
Create Date: 2023-07-04 22:32:18.260512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842b7d247043'
down_revision = 'f900173fcc2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('topic', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'topic')
    # ### end Alembic commands ###
